### ISSUE TITLE
Localhost:8090

### ISSUE THREAD

**Issue by Zaidanaufa** [sindelio/hyperledger-fabric-traceability-framework#18]
after i ran 7.5, i'm still unable to connect to localhost:8090 and the localhost:5000 just show "Hello Traceability framework!" text. What should i do?

**Comment by sindelio** [comment]
Hey Anggita,

Try to apply the troubleshooting techniques described. Also, make sure to
use the exact versions mentioned for all dependencies, else it might not
work.
This repo is getting outdated, I don't have time to maintain it, so in the
worst case scenario go take a look at the official docs from Hyperledger.

Good luck!

**Comment by Zaidanaufa** [comment]
Okay, thanks

**Comment by ufuf** [comment]
@Zaidanaufa if you are still looking for an answer

Explorer images are set as latest but a lot has changed since this repo was built.
You need to set version accordingly. I tried with this and it is working.

image: hyperledger/explorer-db:latest -> image: hyperledger/explorer-db:1.0.0-rc2
image: hyperledger/explorer:latest -> image: hyperledger/explorer:1.0.0-rc2
